version: 0.2

env:
  variables:
    ARN: "arn:aws:secretsmanager:ap-southeast-2:824344348657:secret:portfolio_emailjs-hVgF3e"
    S3_BUCKET: 
  secrets-manager:
    NEXT_PUBLIC_EMAILJS_SERVICE_ID: $ARN:serviceID
    NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: $ARN:templateID
    NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: $ARN:publicKey

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install
  build:
    commands:
      - echo building...
      - npm run build
  post_build:
    commands:
      - echo push artifacts to s3 bucket....
      - aws s3 cp build s3:// ${S3_BUCKET} --recursive
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build