version: 0.2

env:
  variables:
    ARN: "arn:aws:secretsmanager:ap-southeast-2:824344348657:secret:portfolio_emailjs-hVgF3e"
    #S3_BUCKET: "arn:aws:s3:::eden-portfolio"
  secrets-manager:
    NEXT_PUBLIC_EMAILJS_SERVICE_ID: $ARN:serviceID
    NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: $ARN:templateID
    NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: $ARN:publicKey

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: out
cache:
  paths:
    - 'node_modules/**/*' # Cache `node_modules` for faster `yarn` or `npm i`
    - '.next/cache/**/*' # Cache Next.js for faster application rebuilds